/control/verbose  0 
/run/verbose      0     
/event/verbose    0 
/tracking/verbose 0 

/Xe/detector/setLXeScintillation true
/Xe/detector/setLXeRefractionIndex [LXeR]

/Xe/detector/setTeflonReflectivity [LXeTR]
/Xe/detector/setGXeTeflonReflectivity [GXeTR]

/Xe/detector/setLXeAbsorbtionLength [LXeAbsL] 
/Xe/detector/setGXeAbsorbtionLength [GXeAbsL]
/Xe/detector/setLXeRayScatterLength [LXeRSL]

/Xe/detector/setTopScreeningMeshTransparency 0.966
/Xe/detector/setAnodeMeshTransparency 0.905
/Xe/detector/setGateMeshTransparency 0.931
/Xe/detector/setCathodeMeshTransparency 0.972
/Xe/detector/setBottomScreeningMeshTransparency 0.972

/run/random/setRandomSeed 0

/xe/gun/particle opticalphoton
/xe/gun/energy   6.98 eV

/xe/gun/type   Volume
/xe/gun/shape  Cylinder

# in the TPC, above cathode
#/xe/gun/center 0. 0. -483.5 mm
#/xe/gun/halfz  483.5  mm
#/xe/gun/radius 479.25  mm

# in the TPC, also below cathode
/xe/gun/center 0. 0. -522.3 mm
/xe/gun/halfz  522.3  mm
/xe/gun/radius 479.25  mm

# not used (see preinit.mac): LXeTop LXeAroundBell
/xe/gun/confine LXe GXe 

#/analysis/settings/setOptStepInfos true
/analysis/settings/setPMTdetails true

# Tree Filling options
/run/writeEmpty true