/control/verbose  0 
/run/verbose      0     
/event/verbose    0 
/tracking/verbose 0 

/Xe/detector/setLXeScintillation true
/Xe/detector/setLXeRefractionIndex [LXeR]

/Xe/detector/setTeflonReflectivity [LXeTR]
/Xe/detector/setGXeTeflonReflectivity [GXeTR]

/Xe/detector/setLXeAbsorbtionLength [LXeAbsL] 
/Xe/detector/setGXeAbsorbtionLength [GXeAbsL]
/Xe/detector/setLXeRayScatterLength [LXeRSL]

/Xe/detector/setTopScreeningMeshTransparency 0.966
/Xe/detector/setAnodeMeshTransparency 0.905
/Xe/detector/setGateMeshTransparency 0.931
/Xe/detector/setCathodeMeshTransparency 0.972
/Xe/detector/setBottomScreeningMeshTransparency 0.972

/run/random/setRandomSeed 0

/xe/gun/particle opticalphoton
/xe/gun/energy   6.98 eV

/xe/gun/type   Volume
/xe/gun/shape  Cylinder

# in the gas gap for S2 generation
/xe/gun/center 0. 0. 4.5 mm
/xe/gun/halfz 0.5 mm
/xe/gun/radius 480.  mm

# only for per PMT maps
# /xe/gun/numberofparticles 2500

# not used (see preinit.mac): LXeTop LXeAroundBell
/xe/gun/confine LXe GXe 

#/analysis/settings/setOptStepInfos true
/analysis/settings/setPMTdetails true

# Tree Filling options
/run/writeEmpty true

